CFLAGS=-Wall -g
clean:
	rm -f ex1 ex3 ex7 ex8 ex9 ex10 ex11 ex12 ex13 ex14 ex15 ex16
all:
	make ex1 ex3 ex7 ex8 ex9 ex10 ex11 ex12 ex13 ex14 ex15 ex16
	./ex1
	./ex3
	./ex7
	./ex8 Chiara
	./ex9
	./ex10 Chiara
	./ex11
	./ex12
	./ex13 tdw is coming to
	./ex14 wow this is ex14
	./ex15
	./ex16
