CFLAGS=-Wall -g
clean:
	rm -f ex1 ex3 ex7 ex8 ex9 ex10 ex11 ex12 ex13
all:
	make ex1 ex3 ex7 ex8 ex9 ex10 ex11 ex12 ex13
	./ex1
	./ex3
	./ex7
	./ex8 Chiara
	./ex9
	./ex10 Chiara
	./ex11
	./ex12
	./ex13 tdw is coming to
